spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sqldb?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: xiaoxu9
  # mybatis配置
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''